# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
Nombre: Armando Rodarte
Carrera: Ingeniería Informática
Email: armando.rodarte1765@alumnos.udg.mx
Sitio Web: https://armandorodxg.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, mi nombre es Armando Rodarte Treto, estoy estudiando la carrera de ingeniería informática, siendo de 5to semestre. He realizado diversos proyectos básicos a lo largo de
  la carrera con C y C++, apenas me estoy adentrando a mas lenguajes y tecnologías como PostgreSQL, Python, HTML, CSS y JS. 
  
content:
  - title: Proyectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        # title: Super awesome project
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: > 
        description: | # this will include new lines to allow paragraphs
          He desarrollado dos proyectos en Python, precisamente con la librería Flet, un framework basado en flutter, adaptado a python.
          Proyecto 1: Plataforma Educativa de Recursos
            Una aplicación que permite a los usuarios subir y compartir productos educativos como recursos, libros, audiolibros y cursos.
          Proyecto 2: MetaCalor - Seguimiento de Calorías y Actividades
            Una aplicación diseñada para registrar alimentos y ejercicios, realizando un seguimiento de las calorías consumidas y quemadas.
            Funciones incluyen el registro de comidas, generación de informes y establecimiento de metas para motivar a los usuarios en su dieta y rutina de ejercicios.
            Además, se plantea la idea de llevar un registro de competencias, mostrandolo en un leadeboard para fomentar la constancia en el cumplimiento de objetivos, para mantener al usuario motivado.

  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Centro Universitario de Ciencias Exactas e Ingenierías
        caption: 2022 - presente
        sub_title: Ingeniería Informática
        quote: >
        description: | # this will include new lines to allow paragraphs
         Cuando ingresé a la carrera, tenia la idea de lo que iba a tratar, sin embargo no tenia conocimiento de nada. Siempre me ha gustado resolver problemas lógicos, las matemáticas y el diseño, lo cual
         fue lo que me hizo decidirme a meterme en Ingeniería, en especial la informática, ya que abordan algunos aspectos de los que me gustan, en el desarrollo web, programación, entre otras cosas.
         Hoy mas que núnca estoy seguro que es esto a lo que me quiero dedicar al haber desarrollado los proyectos anteriormente mencionados.

  - title: Más sobre mi.
    layout: list
    content:
      - layout: right
      title: Mas sobré mi :D
      quote: >
      description: |
       - Me encanta la música, creo escuchar la mayor parte de mi tiempo, me puede gustar todo tipo de música, pero le tengo preferencia la música Hip-Hop, rap y rock.
       - Disfruto leer, en especial temas relacionados sobres psicología. Siempre es algo bueno llevarse conocimiento de vez en cuando en algunos aspectos que no le damos tanta preferencia y
       ver los distintos puntos de vista que tienen las personas. Siempre permanezco dmanera neutral en estos temas, ya que considero que cada persona funciona de manera diferente.
       - Me gusta jugar videojuegos, especialmente con amigos, aca tampoco tengo preferencias por ningún videojuego, simplemente busco algo que me genere diversión y risas.
       Aunque siempre disfruto realizar de actividades si es con compañia, no solamente en videojuegos.
       - El ejercicio también forma parte de mi rutina, aunque no me enfoco en esto al 100%, realmente disfruto hacerlo.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
